cp /lib/aarch64-linux-gnu/libpthread.so.0 /tmp/lib/libpthread.so
cp /lib/aarch64-linux-gnu/librt.so.1 /tmp/lib/librt.so
cp /usr/lib/aarch64-linux-gnu/libglog.so.0 /tmp/lib/libglog.so
cp /usr/lib/aarch64-linux-gnu/libgflags.so.2.2 /tmp/lib/libgflags.so
cp /usr/local/lib/libopencv_calib3d.so.3.4 /tmp/lib/libopencv_calib3d.so
cp /opt/MVS/lib/aarch64/libMvCameraControl.so /tmp/lib/libMvCameraControl.so
cp /home/linaro/workspace/contactless-fingerprint/include/rga/librga.so /tmp/lib/librga.so
cp /usr/local/lib/libopencv_features2d.so.3.4 /tmp/lib/libopencv_features2d.so
cp /usr/local/lib/libopencv_highgui.so.3.4 /tmp/lib/libopencv_highgui.so
cp /usr/local/lib/libopencv_videoio.so.3.4 /tmp/lib/libopencv_videoio.so
cp /usr/local/lib/libopencv_imgcodecs.so.3.4 /tmp/lib/libopencv_imgcodecs.so
cp /usr/local/lib/libopencv_imgproc.so.3.4 /tmp/lib/libopencv_imgproc.so
cp /usr/local/lib/libopencv_flann.so.3.4 /tmp/lib/libopencv_flann.so
cp /usr/local/lib/libopencv_core.so.3.4 /tmp/lib/libopencv_core.so
cp /usr/lib/aarch64-linux-gnu/libstdc++.so.6 /tmp/lib/libstdc++.so
cp /lib/aarch64-linux-gnu/libm.so.6 /tmp/lib/libm.so
cp /lib/aarch64-linux-gnu/libgcc_s.so.1 /tmp/lib/libgcc_s.so
cp /lib/aarch64-linux-gnu/libc.so.6 /tmp/lib/libc.so
cp /lib/aarch64-linux-gnu/libdl.so.2 /tmp/lib/libdl.so
cp /opt/MVS/lib/aarch64/libGCBase_gcc48_v3_0.so /tmp/lib/libGCBase_gcc48_v3_0.so
cp /opt/MVS/lib/aarch64/libGenApi_gcc48_v3_0.so /tmp/lib/libGenApi_gcc48_v3_0.so
cp /opt/MVS/lib/aarch64/libXmlParser_gcc48_v3_0.so /tmp/lib/libXmlParser_gcc48_v3_0.so
cp /usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0 /tmp/lib/libgtk-x11-2.0.so
cp /usr/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0 /tmp/lib/libgdk-x11-2.0.so
cp /usr/lib/aarch64-linux-gnu/libpangocairo-1.0.so.0 /tmp/lib/libpangocairo-1.0.so
cp /usr/lib/aarch64-linux-gnu/libatk-1.0.so.0 /tmp/lib/libatk-1.0.so
cp /usr/lib/aarch64-linux-gnu/libcairo.so.2 /tmp/lib/libcairo.so
cp /usr/lib/aarch64-linux-gnu/libgdk_pixbuf-2.0.so.0 /tmp/lib/libgdk_pixbuf-2.0.so
cp /usr/lib/aarch64-linux-gnu/libgio-2.0.so.0 /tmp/lib/libgio-2.0.so
cp /usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0 /tmp/lib/libpangoft2-1.0.so
cp /usr/lib/aarch64-linux-gnu/libpango-1.0.so.0 /tmp/lib/libpango-1.0.so
cp /usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0 /tmp/lib/libgobject-2.0.so
cp /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 /tmp/lib/libglib-2.0.so
cp /usr/lib/aarch64-linux-gnu/libfontconfig.so.1 /tmp/lib/libfontconfig.so
cp /usr/lib/aarch64-linux-gnu/libfreetype.so.6 /tmp/lib/libfreetype.so
cp /usr/lib/aarch64-linux-gnu/libgthread-2.0.so.0 /tmp/lib/libgthread-2.0.so
cp /lib/aarch64-linux-gnu/libz.so.1 /tmp/lib/libz.so
cp /usr/lib/aarch64-linux-gnu/libjpeg.so.62 /tmp/lib/libjpeg.so
cp /usr/lib/aarch64-linux-gnu/libpng16.so.16 /tmp/lib/libpng16.so
cp /usr/lib/aarch64-linux-gnu/libtiff.so.5 /tmp/lib/libtiff.so
cp /opt/MVS/lib/aarch64/libMathParser_gcc48_v3_0.so /tmp/lib/libMathParser_gcc48_v3_0.so
cp /opt/MVS/lib/aarch64/libLog_gcc48_v3_0.so /tmp/lib/libLog_gcc48_v3_0.so
cp /opt/MVS/lib/aarch64/libNodeMapData_gcc48_v3_0.so /tmp/lib/libNodeMapData_gcc48_v3_0.so
cp /usr/lib/aarch64-linux-gnu/libgmodule-2.0.so.0 /tmp/lib/libgmodule-2.0.so
cp /usr/lib/aarch64-linux-gnu/libX11.so.6 /tmp/lib/libX11.so
cp /usr/lib/aarch64-linux-gnu/libXcomposite.so.1 /tmp/lib/libXcomposite.so
cp /usr/lib/aarch64-linux-gnu/libXdamage.so.1 /tmp/lib/libXdamage.so
cp /usr/lib/aarch64-linux-gnu/libXfixes.so.3 /tmp/lib/libXfixes.so
cp /usr/lib/aarch64-linux-gnu/libXrender.so.1 /tmp/lib/libXrender.so
cp /usr/lib/aarch64-linux-gnu/libXinerama.so.1 /tmp/lib/libXinerama.so
cp /usr/lib/aarch64-linux-gnu/libXi.so.6 /tmp/lib/libXi.so
cp /usr/lib/aarch64-linux-gnu/libXrandr.so.2 /tmp/lib/libXrandr.so
cp /usr/lib/aarch64-linux-gnu/libXcursor.so.1 /tmp/lib/libXcurso
cp /usr/lib/aarch64-linux-gnu/libXext.so.6 /tmp/lib/libXext.so
cp /usr/lib/aarch64-linux-gnu/libpixman-1.so.0 /tmp/lib/libpixman-1.so
cp /usr/lib/aarch64-linux-gnu/libxcb-shm.so.0 /tmp/lib/libxcb-shm.so
cp /usr/lib/aarch64-linux-gnu/libxcb.so.1 /tmp/lib/libxcb.so
cp /usr/lib/aarch64-linux-gnu/libxcb-render.so.0 /tmp/lib/libxcb-render.so
cp /lib/aarch64-linux-gnu/libmount.so.1 /tmp/lib/libmount.so
cp /lib/aarch64-linux-gnu/libselinux.so.1 /tmp/lib/libselinux.so
cp /lib/aarch64-linux-gnu/libresolv.so.2 /tmp/lib/libreso
cp /usr/lib/aarch64-linux-gnu/libharfbuzz.so.0 /tmp/lib/libharfbuzz.so
cp /usr/lib/aarch64-linux-gnu/libthai.so.0 /tmp/lib/libthai.so
cp /usr/lib/aarch64-linux-gnu/libfribidi.so.0 /tmp/lib/libfribidi.so
cp /usr/lib/aarch64-linux-gnu/libffi.so.6 /tmp/lib/libffi.so
cp /lib/aarch64-linux-gnu/libpcre.so.3 /tmp/lib/libpcre.so
cp /lib/aarch64-linux-gnu/libexpat.so.1 /tmp/lib/libexpat.so
cp /lib/aarch64-linux-gnu/libuuid.so.1 /tmp/lib/libuuid.so
cp /usr/lib/aarch64-linux-gnu/libwebp.so.6 /tmp/lib/libwebp.so
cp /usr/lib/aarch64-linux-gnu/libzstd.so.1 /tmp/lib/libzstd.so
cp /lib/aarch64-linux-gnu/liblzma.so.5 /tmp/lib/liblzma.so
cp /usr/lib/aarch64-linux-gnu/libjbig.so.0 /tmp/lib/libjbig.so
cp /usr/lib/aarch64-linux-gnu/libXau.so.6 /tmp/lib/libXau.so
cp /usr/lib/aarch64-linux-gnu/libXdmcp.so.6 /tmp/lib/libXdmcp.so
cp /lib/aarch64-linux-gnu/libblkid.so.1 /tmp/lib/libblkid.so
cp /usr/lib/aarch64-linux-gnu/libgraphite2.so.3 /tmp/lib/libgraphite2.so
cp /usr/lib/aarch64-linux-gnu/libdatrie.so.1 /tmp/lib/libdatrie.so
cp /usr/lib/aarch64-linux-gnu/libbsd.so.0 /tmp/lib/libbsd.so
